### ISSUE TITLE
Image generation code

### ISSUE THREAD

**Issue by GideonFr** [lich99/Stock_CNN#1]
Dear authors, 

This repository does not seem to contain the code to encode time-series data as images as described in your paper. Do you plan on open-sourcing this?

**Comment by lich99** [comment]
Hi GideonFr! This implementation directly uses the pre-processed data provided by the original paper. And you can download it by this link: https://dachxiu.chicagobooth.edu/download/img_data.zip
And I believe it wouldn't take much time to write a python script by yourself to produce your own dataset for the experiment.

**Comment by techietrader** [comment]
Hi @lich99 , Could you share the codes? Also, I want to understand the mapping you did with the output!
How different will the implementations be if used with FastAI?
